In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [7]:
train = pd.read_csv(r"C:\Users\ggomare\Downloads\houseprice2.csv")

In [17]:
test=pd.read_csv(r"C:\Users\ggomare\Downloads\test.csv")

In [18]:
test

area
0   1520
1   1482
2   1589
3  15762
4   1258
5   1478

In [8]:
reg=linear_model.LinearRegression()

In [10]:
train_x=train.drop(columns=['price'],axis=1)

In [14]:
train_y=train['price']

In [15]:
output=reg.fit(train_x,train_y)

In [19]:
result=output.predict(test)

In [20]:
result

array([ 387013.69863014,  381853.76712329,  396383.04794521,
       2320901.71232877,  351437.32876712,  381310.61643836])

In [25]:
house=pd.read_csv(r"C:\Users\ggomare\Downloads\canada_per_capita_income.csv")

In [26]:
house

year  per capita income (US$)
0   1970              3399.299037
1   1971              3768.297935
2   1972              4251.175484
3   1973              4804.463248
4   1974              5576.514583
5   1975              5998.144346
6   1976              7062.131392
7   1977              7100.126170
8   1978              7247.967035
9   1979              7602.912681
10  1980              8355.968120
11  1981              9434.390652
12  1982              9619.438377
13  1983             10416.536590
14  1984             10790.328720
15  1985             11018.955850
16  1986             11482.891530
17  1987             12974.806620
18  1988             15080.283450
19  1989             16426.725480
20  1990             16838.673200
21  1991             17266.097690
22  1992             16412.083090
23  1993             15875.586730
24  1994             15755.820270
25  1995             16369.317250
26  1996             16699.826680
27  1997             17310.757750
28  1998             16622.671870
29  1999             17581.024140
30  2000             18987.382410
31  2001             18601.397240
32  2002             19232.175560
33  2003             22739.426280
34  2004             25719.147150
35  2005             29198.055690
36  2006             32738.262900
37  2007             36144.481220
38  2008             37446.486090
39  2009             32755.176820
40  2010             38420.522890
41  2011             42334.711210
42  2012             42665.255970
43  2013             42676.468370
44  2014             41039.893600
45  2015             35175.188980
46  2016             34229.193630

In [31]:
x1_train=house.drop(columns=['per capita income (US$)'] ,axis=1)

In [32]:
y1_train=house['per capita income (US$)']

In [33]:
reg1=linear_model.LinearRegression()

In [34]:
out=reg1.fit(x1_train,y1_train)

In [37]:
out.predict([[2020]])

C:\Users\ggomare\Anaconda3\envs\GajananRameshGomare\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41288.69409442])

In [3]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as py
import seaborn as sn
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
digits=load_digits()

In [5]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(digits.data,digits.target,test_size=0.30)

In [8]:
model1=LogisticRegression()
model1.fit(X_train,Y_train)
model1.score(X_test,Y_test)

C:\Users\ggomare\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [9]:
model2=SVC()
model2.fit(X_train,Y_train)
model2.score(X_test,Y_test)

0.9777777777777777

In [10]:
model3=RandomForestClassifier()
model3.fit(X_train,Y_train)
model3.score(X_test,Y_test)

0.9666666666666667

In [17]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [18]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [19]:
def get_score(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

In [28]:
Score_lo=[]
Score_svm=[]
Score_rf=[]

In [29]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [42]:
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,Y_train,Y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    Score_lo.append(get_score(LogisticRegression(max_iter=10000),X_train,X_test,Y_train,Y_test))
    Score_svm.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))
    Score_rf.append(get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test))

In [43]:
set(Score_lo)

{0.8931552587646077,
 0.9148580968280468,
 0.9165275459098498,
 0.9198664440734557,
 0.9232053422370617,
 0.9282136894824707,
 0.9415692821368948}

In [44]:
set(Score_svm)

{0.9549248747913188, 0.9666110183639399, 0.9816360601001669}

In [45]:
set(Score_rf)

{0.9181969949916527,
 0.9215358931552587,
 0.9232053422370617,
 0.9248747913188647,
 0.9265442404006677,
 0.9315525876460768,
 0.9332220367278798,
 0.9382303839732888,
 0.9432387312186978,
 0.9499165275459098,
 0.9515859766277128,
 0.9532554257095158,
 0.9549248747913188,
 0.9599332220367279,
 0.9616026711185309,
 0.9632721202003339}

In [47]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=10000),digits.data,digits.target)

array([0.925     , 0.875     , 0.93871866, 0.93314763, 0.89693593])